#!/bin/bash
# Convert surf files from freesurfer into object files

FREESURFER_HOME=/Applications/Neuroradiology/freesurfer
SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
SCRIPT_DIR_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SUBJECT_ROOT="$1/../"
SUBJECT_MODEL_PATH="$SUBJECT_ROOT/model"



# Check Passed Arguments
if [ $# -gt 1 ]
then
    echo "only give command single surf directory"
    exit 1
elif [ $# == 0 ]
then
    echo "surfFldr2obj"
    echo "convert freesurfer surf folder pial surfaces to .obj files"
    echo "Nathan M. Cross 2017"
    echo 'ex: surfFldr2obj $FREESURFER_HOME/subjects/subj1/surf'
    exit 1
fi

if [ ! -d "$1" ]
then
    echo "only accepts surf directory from freesurfer"
    exit 1
fi

# Check Requisite installation of gawk
if [ ! $(which gawk) ]
then
    echo "Gawk not installed, try:"
    echo "   sudo port install gawk"
    exit 1
fi

#make folder for obj and other 3D models
if [ ! -d "$SUBJECT_MODEL_PATH" ]
then
    mkdir "$SUBJECT_MODEL_PATH" 
fi


# convert pial surface
echo "-> converting surf to .srf"
$FREESURFER_HOME/bin/mris_convert "$1"/lh.pial "$SUBJECT_MODEL_PATH"/lh.pial.asc
mv "$SUBJECT_MODEL_PATH"/lh.pial.asc "$SUBJECT_MODEL_PATH"/lh.pial.srf
$FREESURFER_HOME/bin/mris_convert "$1"/rh.pial "$SUBJECT_MODEL_PATH"/rh.pial.asc
mv "$SUBJECT_MODEL_PATH"/rh.pial.asc "$SUBJECT_MODEL_PATH"/rh.pial.srf

# convert srf file to .obj format
echo "-> converting .srf to Waveform .obj format"
"$SCRIPT_DIR_PATH/srf2obj" "$SUBJECT_MODEL_PATH"/lh.pial.srf > "$SUBJECT_MODEL_PATH"/lh.pial.obj
"$SCRIPT_DIR_PATH/srf2obj" "$SUBJECT_MODEL_PATH"/rh.pial.srf > "$SUBJECT_MODEL_PATH"/rh.pial.obj

echo "-> conversion complete:"
echo "   > model/lh.pial.obj"
echo "   > model/rh.pial.obj"
echo "   > moedl/fused.pial.obj

